GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/63674dc73d0eb890be58aa33

###
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley", "lastName":"Weaver", "email":"aWeaver@test.com", "favoriteColor":"Brown", "birthday":"06/19/2000"
}

###
PUT http://localhost:3000/contacts/63674db03d0eb890be58aa32 HTTP/1.1
Content-Type: application/json

{
   "firstName":"Sarah","lastName":"Birch","email":"amazingwoman@test.com","favoriteColor":"Green","birthday":"12/12/20"
}

###
DELETE http://localhost:3000/contacts/63696809802fa2dd326cce27